import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Kitaplar sidebar configuration
const sidebars: SidebarsConfig = {
  kitaplarSidebar: [

    // Introduction document
    'intro',

    // ASP Güncesi kitabı
    {
      type: 'category',
      label: 'ASP Güncesi',
      link: {
        type: 'doc',
        id: 'asp-guncesi/asp-guncesi-giris',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'asp-guncesi',
        },
      ],
    },    

    // Donanım Girişimciliği kitabı
    {
      type: 'category',
      label: 'Donanım Girişimciliği',
      link: {
        type: 'doc',
        id: 'donanim-girisimciligi/donanim-girisimciligi-giris',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'donanim-girisimciligi',
        },
      ],
    },
  ],
};

export default sidebars;
